### ISSUE TITLE
User Story: Messages

### ISSUE THREAD

**Issue by JulianeGampe** [JulianeGampe/language-school#31]
As a **student/admin** I can **see messages on the screen** so that **I know the result of my input**

## Acceptance criteria

* Messages will appear on screen to notify of the most important actions.

## Tasks

- [x] Import messages and add message tags to settings.py
- [x] Display messages in base.html + set a timeout function for the message
- [x] Add the messages to the views
